-- AddForeignKey
ALTER TABLE `BOLTZ_PRODUCTS` ADD CONSTRAINT `BOLTZ_PRODUCTS_category_id_fkey` FOREIGN KEY (`category_id`) REFERENCES `BOLTZ_CATEGORIES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BOLTZ_PRODUCTS` ADD CONSTRAINT `BOLTZ_PRODUCTS_affiliate_id_fkey` FOREIGN KEY (`affiliate_id`) REFERENCES `BOLTZ_AFFILIATES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
